APP_TITLE = "Memorie, ba"
FPS = 60

### DIMENSIONS ###
WINDOW_WIDTH = 1536
WINDOW_HEIGHT = 864
BOARD_WIDTH = 6
BOARD_HEIGHT = 5
BOX_SIZE = 130
GAP_SIZE = 10
LEFT_MARGIN = int((WINDOW_WIDTH - (BOARD_WIDTH * (BOX_SIZE + GAP_SIZE))) / 2)
TOP_MARGIN = int((WINDOW_HEIGHT - (BOARD_HEIGHT * (BOX_SIZE + GAP_SIZE))) / 2)
HIGHLIGHT_BORDER_SIZE = 5
TEXT_LEFT_MARGIN = 35
TEXT_TOP_MARGIN = 20
TEXT_ROW_HEIGHT = 50

TRANSITION_STEPS = 20
TRANSITION_TIME = 300

BOX_REVEAL_SPEED = 7
NR_REVEALED_BOXES = 10

NR_OF_LEVELS = 3

END_LEVEL_FLASHES = 10

### COLORS ###
GRAY     = (100, 100, 100)
NAVY_BLUE = ( 60,  60, 100)
WHITE    = (255, 255, 255)
BLUE     = (  0,   0, 255)
ORANGE   = (255, 128,   0)
LIGHT_ORANGE = (255, 191, 15)

### TEXT ###
TEXT_FONT = "lucidasans"
#TEXT_FONT = "twcen"
TEXT_FONT_SIZE = 20
TEXT_COLOR = LIGHT_ORANGE

MAX_NAME_LENGTH = 24

BG_COLOR = NAVY_BLUE
LIGHT_BG_COLOR = GRAY
BOX_COLOR = WHITE
HIGHLIGHT_COLOR = LIGHT_ORANGE

### IMAGES ###

### SOUNDS ###
SERGHEI_SOUND_PATH = "Music//SERGHEI_RAS.ogg"
BADEA_SOUND_PATH = "Music//BADEA_1.ogg"
DUMITRESCU_SOUND_PATH = "Music//DUMITRESCU_1.ogg"
INTELIGENT_SOUND_PATH = "Music//INTELIGENT_1.ogg"
MARLANU_SOUND_PATH = "Music//MARLANU_1.ogg"
SILVIU_SOUND_PATH = "Music//SILVIU_1.ogg"
PROSTAMOL_SOUND_PATH = "Music//PROSTAMOL_1.ogg"
GUTA_SOUND_PATH = "Music//GUTA_1.ogg"
#JEREMY_SOUND_PATH = "Music//JEREMY_1.ogg"
ROMEO_SOUND_PATH = "Music//ROMEO_1.ogg"
DINU_SOUND_PATH = "Music//DINU_1.ogg"
WELCOME_SONG_PATH = "Music//W_FRESH.ogg"

### VOLUME ###
NORMAL_VOLUME = 0.35
LOW_VOLUME = 0.1
VOLUME_INCREMENT = 0.01

### RESULTS ###
TABLE_ENTRIES = 10
