APP_TITLE = "Memorie, ba"
FPS = 60

### DIMENSIONS ###
WINDOW_WIDTH = 1536
WINDOW_HEIGHT = 864
BOARD_WIDTH = 6
BOARD_HEIGHT = 5
BOX_SIZE = 130
GAP_SIZE = 10
LEFT_MARGIN = int((WINDOW_WIDTH - (BOARD_WIDTH * (BOX_SIZE + GAP_SIZE))) / 2)
TOP_MARGIN = int((WINDOW_HEIGHT - (BOARD_HEIGHT * (BOX_SIZE + GAP_SIZE))) / 2)
HIGHLIGHT_BORDER_SIZE = 5
TEXT_LEFT_MARGIN = 35
TEXT_TOP_MARGIN = 20
TEXT_ROW_HEIGHT = 50

DOUBLE_MONEY_BOX_LEFT = WINDOW_WIDTH - 200
DOUBLE_MONEY_BOX_TOP = WINDOW_HEIGHT - 200
DOUBLE_MONEY_BOX_WIDTH = 125
NR_PREV_COLORS = 7

TRANSITION_STEPS = 20
TRANSITION_TIME = 300

BOX_REVEAL_SPEED = 6
NR_REVEALED_BOXES = 10

NR_OF_LEVELS = 3

END_LEVEL_FLASHES = 10

INCREASE_MONEY_AMOUNT = 0.1

### COLORS ###
GRAY     = (100, 100, 100)
NAVY_BLUE = ( 60,  60, 100)
WHITE    = (255, 255, 255)
BLUE     = (  0,   0, 255)
ORANGE   = (255, 128,   0)
LIGHT_ORANGE = (255, 191, 15)
RED = (145, 0, 0)
GOLD = (235, 202, 106)

BG_COLOR = NAVY_BLUE
PACANELE_BG_COLOR = RED
LIGHT_BG_COLOR = GRAY
BOX_COLOR = WHITE
HIGHLIGHT_COLOR = LIGHT_ORANGE
PACANELE_RESULT = GOLD

### TEXT ###
TEXT_FONT = "lucidasans"
TEXT_FONT_SIZE = 20
TEXT_COLOR = LIGHT_ORANGE
PACANELE_FONT = "felixtitling"
PACANELE_FONT_SIZE = 256
PACANELE_FONT_COLOR = GOLD

MAX_NAME_LENGTH = 24

### IMAGES ###

### SOUNDS ###
SERGHEI_SOUND_PATH = "Music//SERGHEI_RAS.ogg"
BADEA_SOUND_PATH = "Music//BADEA_1.ogg"
DUMITRESCU_SOUND_PATH = "Music//DUMITRESCU_1.ogg"
INTELIGENT_SOUND_PATH = "Music//INTELIGENT_1.ogg"
MARLANU_SOUND_PATH = "Music//MARLANU_1.ogg"
SILVIU_SOUND_PATH = "Music//SILVIU_1.ogg"
PROSTAMOL_SOUND_PATH = "Music//PROSTAMOL_1.ogg"
GUTA_SOUND_PATH = "Music//GUTA_1.ogg"
#JEREMY_SOUND_PATH = "Music//JEREMY_1.ogg"
ROMEO_SOUND_PATH = "Music//ROMEO_1.ogg"
DINU_SOUND_PATH = "Music//DINU_1.ogg"
ZMAILI_SOUND_PATH = "Music//ZMAILI_1.ogg"
VELEA_SOUND_PATH = "Music//VELEA_1.ogg"
PITT_SOUND_PATH = "Music//PITT_1.ogg"
POPA_SOUND_PATH = "Music//POPA_1.ogg"
AUSTIN_SOUND_PATH = "Music//AUSTIN_1.ogg"
MARGINEANU_SOUND_PATH = "Music//MARGINEANU_1.ogg"
GEOANA_SOUND_PATH = "Music//GEOANA_1.ogg"
DESPOT_SOUND_PATH = "Music//DESPOT_1.ogg"
BORCEA_SOUND_PATH = "Music//BORCEA_1.ogg"
PRA_SOUND_PATH = "Music//PRA_1.ogg"
JACKSON_SOUND_PATH = "Music//JACKSON_1.ogg"
ROBY_SOUND_PATH = "Music//ROBY_1.ogg"
BIJU_SOUND_PATH = "Music//BIJU_1.ogg"
BRET_SOUND_PATH = "Music//BRET_1.ogg"
STEINER_SOUND_PATH = "Music//STEINER_1.ogg"
HAGI_SOUND_PATH = "Music//HAGI_1.ogg"
IOHANNIS_SOUND_PATH = "Music//IOHANNIS_1.ogg"
GARCEA_SOUND_PATH = "Music//GARCEA_1.ogg"
BECALI_SOUND_PATH = "Music//BECALI_3.ogg"
HOGAN_SOUND_PATH = "Music//HOGAN_2.ogg"
METICUZOLITATE_SOUND_PATH = "Music//METICUZOLITATE_1.ogg"
WELCOME_SONG_PATH = "Music//W_FRESH.ogg"
PACANELE_SONG_PATH = "Music//PACANELE.ogg"

### VOLUME ###
NORMAL_VOLUME = 0.35
LOW_VOLUME = 0.1
VOLUME_INCREMENT = 0.01

### RESULTS ###
TABLE_ENTRIES = 10
